openapi: 3.0.1
info:
  title: Finance App
  description: Finnance application
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Kaloyan Velichkov
    email: kaloyanvellichkov@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.3
servers:
  - url: 'https://financeapp-be.herokuapp.com/'
tags:
  - name: Income
    description: Provides a set of functions to interact with the income data
  - name: Expense
    description: Provides a set of functions to interact with the expense data
  - name: User
    description: Provides a set of functions to manage the user data and session
paths:
  /income/get:
    get:
      tags:
        - Income
      summary: Вземане на приход
      description: Взема приход
      operationId: GetIncome
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                fromDate:
                  type: string
                  format: date-time
                  example: '2022-10-01T13:50:00.000Z'
                toDate:
                  type: string
                  format: date-time
                  example: '2022-10-31T13:50:00.000Z'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - id
                    - userId
                    - date
                    - amount
                    - comment
                  properties:
                    id:
                      type: string
                    userId:
                      type: string
                    date:
                      type: string
                      format: date-time
                      example: '2022-10-09T13:50:00.000Z'
                    amount:
                      type: number
                      example: 2300.2
                    comment:
                      type: string
                      example: Вечеря
        '500':
          description: INTERNAL_SERVER_ERROR
  /income/add:
    post:
      tags:
        - Income
      summary: Добавяне на приход
      description: Добавя приход
      operationId: AddIncome
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - date
                - amount
                - comment
              properties:
                userId:
                  type: string
                date:
                  type: string
                  format: date-time
                  example: '2022-10-09T13:50:00.000Z'
                amount:
                  type: number
                  example: 2300.2
                comment:
                  type: string
                  example: Заплата
      responses:
        '200':
          description: OK
        '500':
          description: INTERNAL_SERVER_ERROR
  /income/update:
    put:
      tags:
        - Income
      summary: Редакторане на приход
      description: Редактира приход
      operationId: UpdateIncome
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - userId
              properties:
                id:
                  type: string
                  description: Income id
                userId:
                  type: string
                date:
                  type: string
                  format: date-time
                  example: '2022-10-09T13:50:00.000Z'
                amount:
                  type: number
                  example: 600.8
                comment:
                  type: string
                  example: Продадох си телефона
      responses:
        '200':
          description: OK
        '500':
          description: INTERNAL_SERVER_ERROR
  /income/delete:
    delete:
      tags:
        - Income
      summary: Изтриване на приход
      description: Изтрива приход
      operationId: DeleteIncome
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - userId
              properties:
                id:
                  type: string
                  description: Income id
                userId:
                  type: string
      responses:
        '200':
          description: OK
        '500':
          description: INTERNAL_SERVER_ERROR
  /expense/get:
    get:
      tags:
        - Expense
      summary: Вземане на разход
      description: Взема разход
      operationId: GetExpense
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                fromDate:
                  type: string
                  format: date-time
                  example: '2022-10-01T13:50:00.000Z'
                toDate:
                  type: string
                  format: date-time
                  example: '2022-10-31T13:50:00.000Z'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - id
                    - userId
                    - date
                    - amount
                    - comment
                  properties:
                    id:
                      type: string
                    userId:
                      type: string
                    date:
                      type: string
                      format: date-time
                      example: '2022-10-09T13:50:00.000Z'
                    amount:
                      type: number
                      example: 2300.2
                    comment:
                      type: string
                      example: Вечеря
        '500':
          description: INTERNAL_SERVER_ERROR
  /expense/add:
    post:
      tags:
        - Expense
      summary: Добавяне на разход
      description: Добавя разход
      operationId: AddExpense
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - date
                - amount
                - comment
              properties:
                userId:
                  type: string
                date:
                  type: string
                  format: date-time
                  example: '2022-10-09T13:50:00.000Z'
                amount:
                  type: number
                  example: 2300.2
                comment:
                  type: string
                  example: Вечеря
      responses:
        '200':
          description: OK
        '500':
          description: INTERNAL_SERVER_ERROR
  /expense/update:
    put:
      tags:
        - Expense
      summary: Редакторане на разход
      description: Редактира разход
      operationId: UpdateExpense
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - userId
              properties:
                id:
                  type: string
                  description: Expense id
                userId:
                  type: string
                date:
                  type: string
                  format: date-time
                  example: '2022-10-09T13:50:00.000Z'
                amount:
                  type: number
                  example: 150.8
                comment:
                  type: string
                  example: Гориво
      responses:
        '200':
          description: OK
        '500':
          description: INTERNAL_SERVER_ERROR
  /expense/delete:
    delete:
      tags:
        - Expense
      summary: Изтриване на разход
      description: Изтрива разход
      operationId: DeleteExpense
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - id
              properties:
                id:
                  type: string
                  description: Expense id
                userId:
                  type: string
      responses:
        '200':
          description: OK
        '500':
          description: INTERNAL_SERVER_ERROR
  /user/register:
    post:
      tags:
        - User
      summary: Регистриране на потребител
      description: Регистрира потребител
      operationId: RegisterUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - firstName
                - lastName
                - password
              properties:
                email:
                  type: string
                  example: example@mail.com
                firstName:
                  type: string
                  example: Pesho
                lastName:
                  type: string
                  example: Shvepsa
                password:
                  type: string
                  example: my_password_123
      responses:
        '200':
          description: OK
        '500':
          description: INTERNAL_SERVER_ERROR
  /user/login:
    post:
      tags:
        - User
      summary: Логване на потребител
      description: Логва потребител
      operationId: LoginUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: example@mail.com
                password:
                  type: string
                  example: my_password_123
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - email
                  - firstName
                  - lastName
                  - password
                properties:
                  id:
                    type: string
                  email:
                    type: string
                    example: example@mail.com
                  firstName:
                    type: string
                    example: Pesho
                  lastName:
                    type: string
                    example: Shvepsa
        '500':
          description: INTERNAL_SERVER_ERROR
  /user/update:
    put:
      tags:
        - User
      summary: Редакторане на потребител
      description: Редактира потребител
      operationId: UpdateUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: string
                  description: User id
                email:
                  type: string
                  example: example@mail.com
                firstName:
                  type: string
                  example: Pesho
                lastName:
                  type: string
                  example: Shvepsa
                password:
                  type: string
                  example: my_password_123
      responses:
        '200':
          description: OK
        '500':
          description: INTERNAL_SERVER_ERROR
