openapi: 3.0.1
info:
  title: Finance App
  description: Finnance application
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Kaloyan Velichkov
    email: kaloyanvellichkov@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.3

servers:
  - url: 'https://financeapp-be.herokuapp.com/'

tags:
  - name: Income
    description: 'Provides a set of functions to interact with the income data'

  - name: Expense
    description: 'Provides a set of functions to interact with the expense data'

  - name: User
    description: 'Provides a set of functions to manage the user data and session'

paths:
  '/income/get':
    $ref: './resources/finance/income/GetIncome.yml'
  '/income/add':
    $ref: './resources/finance/income/AddIncome.yml'
  '/income/update':
    $ref: './resources/finance/income/UpdateIncome.yml'
  '/income/delete':
    $ref: './resources/finance/income/DeleteIncome.yml'

  '/expense/get':
    $ref: './resources/finance/expense/GetExpense.yml'
  '/expense/add':
    $ref: './resources/finance/expense/AddExpense.yml'
  '/expense/update':
    $ref: './resources/finance/expense/UpdateExpense.yml'
  '/expense/delete':
    $ref: './resources/finance/expense/DeleteExpense.yml'

  '/user/register':
    $ref: './resources/user/RegisterUser.yml'
  '/user/login':
    $ref: './resources/user/LoginUser.yml'